name: CI

on: [push, pull_request]

jobs:
  test-windows:
    name: Test - Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Fetch all history and metadata
      run: |
        git fetch --prune --unshallow
        git checkout -b pr
        git branch -f master origin/master

    - name: Install clang-format
      run: |
        choco install llvm --version 10.0.0

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install wpiformat
      run: |
        cd wpiformat
        pip3 install -e .

    - name: Run unit tests
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        cd wpiformat
        # This pytest dependency is installed manually before the script ends
        # because it returns a nonzero exit code due to a warning. If it were
        # installed by "setup.py test", it would make "setup.py test" report an
        # error.
        pip3 install iniconfig
        python setup.py test

    - name: wpiformat - whole repo
      run: |
        python -m wpiformat -v

    - name: wpiformat - one file
      run: |
        cd wpiformat
        python -m wpiformat -f wpiformat/__init__.py -v

    - name: wpiformat - absolute path to file
      run: python -m wpiformat -f /home/runner/work/styleguide/styleguide/wpiformat/wpiformat/__init__.py -v

    - name: wpiformat - multiple files
      run: |
        cd wpiformat
        python -m wpiformat -f wpiformat/__init__.py wpiformat/__main__.py -v

    - name: wpiformat - directory
      run: |
        cd wpiformat
        python -m wpiformat -f wpiformat -v

    - name: Ensure formatter made no changes
      run: git --no-pager diff --exit-code HEAD
  test-linux:
    name: Test - Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Fetch all history and metadata
      run: git fetch --prune --unshallow

    - name: Ensure master branch exists
      run: git branch master origin/master

    - name: Install clang-format
      run: |
        sudo apt-get install clang-format-10

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install wpiformat
      run: |
        cd wpiformat
        pip3 install -e .

    - name: Run unit tests
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        cd wpiformat
        python3 setup.py test

    - name: wpiformat - whole repo
      run: |
        python3 -m wpiformat -v

    - name: wpiformat - one file
      run: |
        cd wpiformat
        python3 -m wpiformat -f wpiformat/__init__.py -v

    - name: wpiformat - absolute path to file
      run: python3 -m wpiformat -f /home/runner/work/styleguide/styleguide/wpiformat/wpiformat/__init__.py -v

    - name: wpiformat - multiple files
      run: |
        cd wpiformat
        python3 -m wpiformat -f wpiformat/__init__.py wpiformat/__main__.py -v

    - name: wpiformat - directory
      run: |
        cd wpiformat
        python3 -m wpiformat -f wpiformat -v

    - name: Ensure formatter made no changes
      run: git --no-pager diff --exit-code HEAD
  test-macos:
    name: Test - macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Fetch all history and metadata
      run: |
        git fetch --prune --unshallow
        git checkout -b pr
        git branch -f master origin/master

    - name: Install clang-format
      run: |
        brew install clang-format

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install wpiformat
      run: |
        cd wpiformat
        pip3 install -e .

    - name: Run unit tests
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        cd wpiformat
        python3 setup.py test

    - name: wpiformat - whole repo
      run: |
        python3 -m wpiformat -v

    - name: wpiformat - one file
      run: |
        cd wpiformat
        python3 -m wpiformat -f wpiformat/__init__.py -v

    - name: wpiformat - absolute path to file
      run: python3 -m wpiformat -f /Users/runner/work/styleguide/styleguide/wpiformat/wpiformat/__init__.py -v

    - name: wpiformat - multiple files
      run: |
        cd wpiformat
        python3 -m wpiformat -f wpiformat/__init__.py wpiformat/__main__.py -v

    - name: wpiformat - directory
      run: |
        cd wpiformat
        python3 -m wpiformat -f wpiformat -v

    - name: Ensure formatter made no changes
      run: git --no-pager diff --exit-code HEAD
